# Generated by Django 4.1.3 on 2023-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
